### ISSUE TITLE
Why does the result after autohic adjustment look worse than the result before adjustment, and how should this situation be adjusted

### ISSUE THREAD

**Issue by lstxmu** [Jwindler/AutoHiC#23]
Why does the result after autohic adjustment look worse than the result before adjustment, and how should this situation be adjusted?

[AutoHiC Report at Wed Apr 17 01_31_42 2024.pdf](https://github.com/Jwindler/AutoHiC/files/15004055/AutoHiC.Report.at.Wed.Apr.17.01_31_42.2024.pdf)

How to specify chromosomal data in Autohic, for example 2n=66.

**Comment by Jwindler** [comment]
Judging from your results, your scaffold works very well, with no translocation and inversion errors. You think the adjustment effect is getting worse, just because of the color threshold of the contact heatmap, but in fact the effect is better. But the problem is, from the contact heatmap, you may have 31 chromosomes. If you have experimental data proving that there are 33 chromosomes, I suggest you use reference [methods](https://github.com/Jwindler/AutoHiC?tab=readme-ov-file#split-chromosome-optional) to manually divide the chromosomes and compare them with homologous species to check whether there are chromosome fusion events, etc.

**Comment by Jwindler** [comment]
The AutoHiC algorithm employs image detection techniques to assign chromosomes based on contact heatmaps. One may infer the chromosome number from an adjusted heatmap. However, it is possible that the number of chromosomes ultimately divided may be inconsistent with the actual situation due to the influence of the visual color threshold or other issues with the data.
